---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ease
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id:
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
