---
apiVersion: v1
offerings:
  - name: testing-deploy-arch-ibm-ease
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 19d2e811-45f1-4705-8c9b-b3252ee44711
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
