# More info about this file at https://github.com/terraform-ibm-modules/common-pipeline-assets/blob/main/.github/workflows/terraform-test-pipeline.md#cra-config-yaml
version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "solutions/fully-configurable" # Target directory for CRA scan. If not provided, the CRA Scan will not be run.
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json" # CRA Ignore file to use. If not provided, it checks the repo root directory for `cra-tf-validate-ignore-rules.json`
    PROFILE_ID: "fe96bd4d-9b37-40f2-b39f-a62760e326a3"         # SCC profile ID (currently set to 'IBM Cloud Framework for Financial Services' '1.7.0' profile).
    CRA_ENVIRONMENT_VARIABLES:  # An optional map of environment variables for CRA, where the key is the variable name and value is the value. Useful for providing TF_VARs.
      TF_VAR_region: "us-east"
      TF_VAR_config_repo: "https://github.com/tim-openliberty-appflow-test/sample-getting-started-config"
      TF_VAR_source_repo: "https://github.com/tim-openliberty-appflow-test/sample-getting-started"
      TF_VAR_repos_git_token_secret_crn: "crn:v1:bluemix:public:secrets-manager:us-south:a/abac0df06b644a9cabc6e44f55b3880e:79c6d411-c18f-4670-b009-b0044a238667:secret:825a3797-1bc8-f47a-611a-c9bd2b0ef846" # pragma: allowlist secret
      TF_VAR_subscription_id_secret_crn: "crn:v1:bluemix:public:secrets-manager:us-south:a/abac0df06b644a9cabc6e44f55b3880e:79c6d411-c18f-4670-b009-b0044a238667:secret:71363d27-db8d-dd07-c72b-59ecb3884a8f" # pragma: allowlist secret
      TF_VAR_subscription_id: "null" # pragma: allowlist secret
      TF_VAR_existing_resource_group_name: "geretain-test-e4j"
      TF_VAR_prefix: "e4j-cra"
      TF_VAR_provider_visibility: "public"
